[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.9"
name = "optimuskg"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "ipython>=8.10",
    "jupyterlab>=3.0",
    "notebook",
    "kedro[jupyter]~=0.19.10",
    "kedro-datasets[pandas-csvdataset]>=3.0",
    "kedro-airflow~=0.5",
    "obonet>=1.1.0",
    "bs4>=0.0.2",
    "goatools>=1.4.12",
    "result>=0.17.0",
    "ruff>=0.1.15",
]

[project.scripts]
"optimuskg" = "optimuskg.__main__:main"

[project.entry-points."kedro.hooks"]

[project.optional-dependencies]
docs = [
    "docutils<0.18.0",
    "sphinx~=3.4.3",
    "sphinx_rtd_theme==0.5.1",
    "nbsphinx==0.8.1",
    "sphinx-autodoc-typehints==1.11.1",
    "sphinx_copybutton==0.3.1",
    "ipykernel>=5.3, <7.0",
    "Jinja2<3.1.0",
    "myst-parser~=0.17.2",
]
dev = [
    "pytest-cov~=3.0",
    "pytest-mock>=1.7.1, <2.0",
    "pytest~=7.2",
    "pre-commit>=4.0.1",
    "ruff~=0.1.8",
]

[tool.setuptools.dynamic]
version = {attr = "optimuskg.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.kedro]
package_name = "optimuskg"
project_name = "optimuskg"
kedro_init_version = "0.19.9"
tools = ['Linting', 'Testing', 'Custom Logging', 'Documentation', 'Data Structure']
example_pipeline = "True"
source_dir = "src"

[tool.pytest.ini_options]
addopts = """
--cov-report html \
--cov src -ra
"""
filterwarnings = [
  "error:Sparse:FutureWarning",
  "error:The SparseArray:FutureWarning",
  "ignore::DeprecationWarning",
]

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff]
line-length = 88
show-fixes = true
exclude = ["dags/*"]
lint.select = [
    "F",   # Pyflakes
    "W",   # pycodestyle
    "E",   # pycodestyle
    "I",   # isort
    "UP",  # pyupgrade
    "PL",  # Pylint
    "T201", # Print Statement
]
lint.ignore = ["E501"]  # Ruff format takes care of line-too-long

